---
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  podspec:
    name: Lint Podspec for ${{ matrix.platform }}
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [ios, osx, tvos, watchos]
    steps:
      - uses: actions/checkout@v2
      - name: Lint Podspec
        run: pod lib lint --platforms=${{ matrix.platform }}

  xcodebuild:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: "xcodebuild (iOS 15.2, Xcode 13.2.1)"
            os: macos-11
            xcode-version: "13.2.1"
            sdk: iphonesimulator15.2
            destination: "platform=iOS Simulator,OS=15.2,name=iPhone 13"
          - name: "xcodebuild (tvOS 15.2, Xcode 13.2.1)"
            os: macos-11
            xcode-version: "13.2.1"
            sdk: appletvsimulator15.2
            destination: "platform=tvOS Simulator,OS=15.2,name=Apple TV"
          - name: "xcodebuild (macOS 12.1, Xcode 13.2.1)"
            os: macos-11
            xcode-version: "13.2.1"
            sdk: macosx12.1
            destination: "platform=OS X"
          - name: "xcodebuild (watchOS 8.3, Xcode 13.2.1)"
            os: macos-11
            xcode-version: "13.2.1"
            sdk: watchos8.3
            destination: "platform=watchOS Simulator,OS=8.3,name=Apple Watch Series 7 - 45mm"
          - name: "xcodebuild (iOS 14.0, Xcode 12.0.1)"
            os: macos-10.15
            xcode-version: "12"
            sdk: iphonesimulator14.0
            destination: "platform=iOS Simulator,OS=14.0,name=iPhone 11"
          - name: "xcodebuild (tvOS 14.0, Xcode 12.0.1)"
            os: macos-10.15
            xcode-version: "12"
            sdk: appletvsimulator14.0
            destination: "platform=tvOS Simulator,OS=14.0,name=Apple TV"
          - name: "xcodebuild (macOS 10.15, Xcode 12.0.1)"
            os: macos-10.15
            xcode-version: "12"
            sdk: macosx10.15
            destination: "platform=OS X"
          - name: "xcodebuild (watchOS 7.0, Xcode 12.0.1)"
            os: macos-10.15
            xcode-version: "12"
            sdk: watchos7.0
            destination: "platform=watchOS Simulator,OS=7.0,name=Apple Watch Series 6 - 44mm"
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build & Test
        run: |
          xcodebuild \
            -scheme TheLibrary \
            -sdk "${{ matrix.sdk }}" \
            -destination "${{ matrix.destination }}" \
            clean test | xcpretty -c;
